### ISSUE TITLE
`todo-list` app freezes on some `Redo` actions

### ISSUE THREAD

**Issue by scott-maddox** [enthought/ets-examples#15] opened 2019-02-27 16:39 UTC
The `todo-list` app occasionally freezes on `Redo`. To reproduce:

1. Start the app under the edm env below: `cd todo-list` and `python -m todo_list.app`.
2. Press `New Item` 5 times.
3. Press `Edit > Undo` 5 times.
4. Press `Edit > Redo`.

Expected Result: one empty task should be visible.
Actual Result: the app freezes (spinning beach ball on macOS), and must be force quit.

edm env:

```json
{
    "mark": [
        {
            "name": "appdirs",
            "state": "auto"
        },
        {
            "name": "distribute_remove",
            "state": "auto"
        },
        {
            "name": "libxml2",
            "state": "auto"
        },
        {
            "name": "libxslt",
            "state": "auto"
        },
        {
            "name": "packaging",
            "state": "auto"
        },
        {
            "name": "pip",
            "state": "manual"
        },
        {
            "name": "pyface",
            "state": "auto"
        },
        {
            "name": "pygments",
            "state": "auto"
        },
        {
            "name": "pyparsing",
            "state": "auto"
        },
        {
            "name": "pyside",
            "state": "manual"
        },
        {
            "name": "qt",
            "state": "auto"
        },
        {
            "name": "setuptools",
            "state": "manual"
        },
        {
            "name": "shiboken",
            "state": "auto"
        },
        {
            "name": "six",
            "state": "auto"
        },
        {
            "name": "traits",
            "state": "manual"
        },
        {
            "name": "traitsui",
            "state": "manual"
        }
    ],
    "metadata_version": "1.0",
    "modifiers": {
        "allow_any": [],
        "allow_newer": [],
        "allow_older": []
    },
    "repositories": {
        "packages": [
            "enthought/commercial",
            "enthought/free"
        ],
        "runtimes": [
            "enthought/free"
        ]
    },
    "requirements": [
        "appdirs-1.4.3-1",
        "distribute_remove-1.0.0-4",
        "libxml2-2.9.7-1",
        "libxslt-1.1.30-1",
        "packaging-16.8-3",
        "pip-18.1-1",
        "pyface-6.0.0-2",
        "pygments-2.2.0-1",
        "pyparsing-2.2.0-1",
        "pyside-1.2.2-15",
        "qt-4.8.7-10",
        "setuptools-38.2.5-2",
        "shiboken-1.2.2-14",
        "six-1.11.0-1",
        "traits-5.0.0-1",
        "traitsui-6.0.0-2"
    ],
    "runtime": {
        "implementation": "cpython",
        "platform": "osx_x86_64",
        "platform_abi": "darwin",
        "version": "2.7.13+3"
    }
}
```

**Comment by corranwebster** [comment] 2019-02-27 17:04
I can reproduce.

**Comment by corranwebster** [comment] 2019-02-28 12:59
Looking at this, at least part of the problem is that the TraitsUI Undo/Redo is working at a very superficial level of setting/unsetting values.  In this case there are two problems:

- the Undo/Redo mechanisms try to set read-only properties (like the `remaining` trait)
- they also work only on the items that the editor sees, so for example it sets the `displayed_items` trait, but that has no way of pushing values back to the underlying model.

**Comment by corranwebster** [comment] 2019-03-01 20:55
The freezing should be resolved by https://github.com/enthought/traitsui/pull/510 but there were further issues which mean Undo/Redo doesn't work.  I have removed Undo/Redo for now and will revisit in another example later.

**Closed as completed by corranwebster** 2019-03-01 20:55 UTC
